// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/hqnightbk.tga
gfx/env/hqnightdn.tga
gfx/env/hqnightft.tga
gfx/env/hqnightlf.tga
gfx/env/hqnightrt.tga
gfx/env/hqnightup.tga
hoe.wad
maps/halfquake.bsp
maps/halfquake10.bsp
maps/halfquake11.bsp
maps/halfquake12.bsp
maps/halfquake2.bsp
maps/halfquake3.bsp
maps/halfquake4.bsp
maps/halfquake5.bsp
maps/halfquake6.bsp
maps/halfquake7.bsp
maps/halfquake8.bsp
maps/halfquake9.bsp
models/hq/barney.mdl
models/hq/crossbow_bolt.mdl
models/hq/headcrab.mdl
models/hq/hgrunt.mdl
models/hq/islave.mdl
models/hq/miniturret.mdl
models/hq/null.mdl
models/hq/p_crossbow.mdl
models/hq/p_crowbar.mdl
models/hq/scientist.mdl
models/hq/turret.mdl
models/hq/v_357.mdl
models/hq/v_9mmar.mdl
models/hq/v_9mmhandgun.mdl
models/hq/v_crossbow.mdl
models/hq/v_crowbar.mdl
models/hq/v_egon.mdl
models/hq/v_gauss.mdl
models/hq/v_rpg.mdl
models/hq/v_satchel.mdl
models/hq/v_satchel_radio.mdl
models/hq/v_shotgun.mdl
models/hq/v_tripmine.mdl
models/hq/w_9mmarclip.mdl
models/hq/w_battery.mdl
models/hq/w_crossbow.mdl
models/hq/w_crowbar.mdl
models/hq/w_medkit.mdl
models/hq/w_suit.mdl
sound/hq/ambience/backstage.wav
sound/hq/ambience/backstage2.wav
sound/hq/ambience/backstage3.wav
sound/hq/ambience/bj_01.wav
sound/hq/ambience/en_bg.wav
sound/hq/ambience/en_suckin.wav
sound/hq/ambience/jm_01.wav
sound/hq/ambience/ms_01.wav
sound/hq/buttons/hq1/bell1.wav
sound/hq/buttons/hq1/blip1.wav
sound/hq/buttons/hq1/blip2.wav
sound/hq/buttons/hq1/button1.wav
sound/hq/buttons/hq1/button10.wav
sound/hq/buttons/hq1/button11.wav
sound/hq/buttons/hq1/button2.wav
sound/hq/buttons/hq1/button3.wav
sound/hq/buttons/hq1/button4.wav
sound/hq/buttons/hq1/button5.wav
sound/hq/buttons/hq1/button6.wav
sound/hq/buttons/hq1/button7.wav
sound/hq/buttons/hq1/button8.wav
sound/hq/buttons/hq1/button9.wav
sound/hq/buttons/hq1/latchlocked1.wav
sound/hq/buttons/hq1/latchlocked2.wav
sound/hq/buttons/hq1/latchunlocked1.wav
sound/hq/buttons/hq1/latchunlocked2.wav
sound/hq/buttons/hq1/lever1.wav
sound/hq/buttons/hq1/lever2.wav
sound/hq/buttons/hq1/lever3.wav
sound/hq/buttons/hq1/lever4.wav
sound/hq/buttons/hq1/lever5.wav
sound/hq/buttons/hq1/lightswitch2.wav
sound/hq/buttons/hq1/spark1.wav
sound/hq/buttons/hq1/spark2.wav
sound/hq/buttons/hq1/spark3.wav
sound/hq/buttons/hq1/spark4.wav
sound/hq/buttons/hq1/spark5.wav
sound/hq/buttons/hq1/spark6.wav
sound/hq/common/hq1/bodydrop1.wav
sound/hq/common/hq1/bodydrop2.wav
sound/hq/common/hq1/bodydrop3.wav
sound/hq/common/hq1/bodydrop4.wav
sound/hq/common/hq1/bodysplat.wav
sound/hq/common/hq1/npc_step1.wav
sound/hq/common/hq1/npc_step2.wav
sound/hq/common/hq1/npc_step3.wav
sound/hq/common/hq1/npc_step4.wav
sound/hq/common/hq1/wpn_denyselect.wav
sound/hq/common/hq1/wpn_hudoff.wav
sound/hq/common/hq1/wpn_hudon.wav
sound/hq/common/hq1/wpn_moveselect.wav
sound/hq/common/hq1/wpn_select.wav
sound/hq/common/hq2/bodysplat.wav
sound/hq/debris/hq1/beamstart1.wav
sound/hq/debris/hq1/beamstart10.wav
sound/hq/debris/hq1/beamstart11.wav
sound/hq/debris/hq1/beamstart14.wav
sound/hq/debris/hq1/beamstart15.wav
sound/hq/debris/hq1/beamstart2.wav
sound/hq/debris/hq1/beamstart3.wav
sound/hq/debris/hq1/beamstart4.wav
sound/hq/debris/hq1/beamstart5.wav
sound/hq/debris/hq1/beamstart6.wav
sound/hq/debris/hq1/beamstart7.wav
sound/hq/debris/hq1/beamstart8.wav
sound/hq/debris/hq1/beamstart9.wav
sound/hq/debris/hq1/bustceiling.wav
sound/hq/debris/hq1/bustconcrete1.wav
sound/hq/debris/hq1/bustconcrete2.wav
sound/hq/debris/hq1/bustcrate1.wav
sound/hq/debris/hq1/bustcrate2.wav
sound/hq/debris/hq1/bustcrate3.wav
sound/hq/debris/hq1/bustflesh1.wav
sound/hq/debris/hq1/bustflesh2.wav
sound/hq/debris/hq1/bustglass1.wav
sound/hq/debris/hq1/bustglass2.wav
sound/hq/debris/hq1/bustglass3.wav
sound/hq/debris/hq1/bustmetal1.wav
sound/hq/debris/hq1/bustmetal2.wav
sound/hq/debris/hq1/concrete1.wav
sound/hq/debris/hq1/concrete2.wav
sound/hq/debris/hq1/concrete3.wav
sound/hq/debris/hq1/flesh1.wav
sound/hq/debris/hq1/flesh2.wav
sound/hq/debris/hq1/flesh3.wav
sound/hq/debris/hq1/flesh5.wav
sound/hq/debris/hq1/flesh6.wav
sound/hq/debris/hq1/flesh7.wav
sound/hq/debris/hq1/glass1.wav
sound/hq/debris/hq1/glass2.wav
sound/hq/debris/hq1/glass3.wav
sound/hq/debris/hq1/glass4.wav
sound/hq/debris/hq1/metal1.wav
sound/hq/debris/hq1/metal2.wav
sound/hq/debris/hq1/metal3.wav
sound/hq/debris/hq1/metal4.wav
sound/hq/debris/hq1/metal5.wav
sound/hq/debris/hq1/metal6.wav
sound/hq/debris/hq1/pushbox1.wav
sound/hq/debris/hq1/pushbox2.wav
sound/hq/debris/hq1/pushbox3.wav
sound/hq/debris/hq1/wood1.wav
sound/hq/debris/hq1/wood2.wav
sound/hq/debris/hq1/wood3.wav
sound/hq/debris/hq1/wood4.wav
sound/hq/debris/hq1/zap1.wav
sound/hq/debris/hq1/zap2.wav
sound/hq/debris/hq1/zap3.wav
sound/hq/debris/hq1/zap4.wav
sound/hq/debris/hq1/zap5.wav
sound/hq/debris/hq1/zap6.wav
sound/hq/debris/hq1/zap7.wav
sound/hq/debris/hq1/zap8.wav
sound/hq/doors/hq1/aliendoor1.wav
sound/hq/doors/hq1/aliendoor2.wav
sound/hq/doors/hq1/aliendoor3.wav
sound/hq/doors/hq1/aliendoor4.wav
sound/hq/doors/hq1/aliendoor5.wav
sound/hq/doors/hq1/doormove1.wav
sound/hq/doors/hq1/doormove10.wav
sound/hq/doors/hq1/doormove2.wav
sound/hq/doors/hq1/doormove3.wav
sound/hq/doors/hq1/doormove4.wav
sound/hq/doors/hq1/doormove5.wav
sound/hq/doors/hq1/doormove6.wav
sound/hq/doors/hq1/doormove7.wav
sound/hq/doors/hq1/doormove8.wav
sound/hq/doors/hq1/doormove9.wav
sound/hq/doors/hq1/doorstop1.wav
sound/hq/doors/hq1/doorstop2.wav
sound/hq/doors/hq1/doorstop3.wav
sound/hq/doors/hq1/doorstop4.wav
sound/hq/doors/hq1/doorstop5.wav
sound/hq/doors/hq1/doorstop6.wav
sound/hq/doors/hq1/doorstop7.wav
sound/hq/doors/hq1/doorstop8.wav
sound/hq/doors/hq2/doorstop8.wav
sound/hq/en/en1.wav
sound/hq/en/en10.wav
sound/hq/en/en11.wav
sound/hq/en/en12.wav
sound/hq/en/en13.wav
sound/hq/en/en14.wav
sound/hq/en/en15.wav
sound/hq/en/en16.wav
sound/hq/en/en17.wav
sound/hq/en/en18.wav
sound/hq/en/en19.wav
sound/hq/en/en2.wav
sound/hq/en/en3.wav
sound/hq/en/en4.wav
sound/hq/en/en5.wav
sound/hq/en/en6.wav
sound/hq/en/en7.wav
sound/hq/en/en8.wav
sound/hq/en/en9.wav
sound/hq/fans/hq1/fan1.wav
sound/hq/fans/hq1/fan2.wav
sound/hq/fans/hq1/fan3.wav
sound/hq/fans/hq1/fan4.wav
sound/hq/fans/hq1/fan5.wav
sound/hq/hq/bdeath.wav
sound/hq/hq/bdeath2.wav
sound/hq/hq/bsd.wav
sound/hq/hq/credits.wav
sound/hq/hq/end_part2.wav
sound/hq/hq/fdial1.wav
sound/hq/hq/fdial2.wav
sound/hq/hq/fdial3.wav
sound/hq/hq/fdial4.wav
sound/hq/hq/flush.wav
sound/hq/hq/intro.wav
sound/hq/hq/intro_head.wav
sound/hq/hq/intro_seaoftrees.wav
sound/hq/hq/jr2_end.wav
sound/hq/hq/jr2_end2.wav
sound/hq/hq/man_die_part4.wav
sound/hq/hq/p0_logon.wav
sound/hq/hq/p3_seems.wav
sound/hq/hq/part2.wav
sound/hq/hq/part_4_man_after.wav
sound/hq/hq/secret.wav
sound/hq/hq/victimsmindmalastrome15.wav
sound/hq/hq/wunderground.wav
sound/hq/hq2/amb_ms.wav
sound/hq/hq2/bj_exec2.wav
sound/hq/hq2/ms_ess1.wav
sound/hq/hq2/ms_ess2.wav
sound/hq/hq2/ms_ess3.wav
sound/hq/hq_complete_soundtrack/21_hollow_hallways.mp3
sound/hq/hq_complete_soundtrack/22_wunderground.mp3
sound/hq/hq_complete_soundtrack/23_somos1.mp3
sound/hq/materials.txt
sound/hq/pestilence/bj.wav
sound/hq/plats/hq1/bigmove1.wav
sound/hq/plats/hq1/bigmove2.wav
sound/hq/plats/hq1/bigstop1.wav
sound/hq/plats/hq1/bigstop2.wav
sound/hq/plats/hq1/elevbell1.wav
sound/hq/plats/hq1/elevmove1.wav
sound/hq/plats/hq1/elevmove2.wav
sound/hq/plats/hq1/elevmove3.wav
sound/hq/plats/hq1/freightmove1.wav
sound/hq/plats/hq1/freightmove2.wav
sound/hq/plats/hq1/freightstop1.wav
sound/hq/plats/hq1/heavymove1.wav
sound/hq/plats/hq1/heavystop1.wav
sound/hq/plats/hq1/heavystop2.wav
sound/hq/plats/hq1/platmove1.wav
sound/hq/plats/hq1/platstop1.wav
sound/hq/plats/hq1/rackmove1.wav
sound/hq/plats/hq1/railmove1.wav
sound/hq/plats/hq1/railstop1.wav
sound/hq/plats/hq1/squeekmove1.wav
sound/hq/plats/hq1/squeekstop1.wav
sound/hq/plats/hq1/talkmove1.wav
sound/hq/plats/hq1/talkmove2.wav
sound/hq/plats/hq1/talkstop1.wav
sound/hq/plats/hq1/train1.wav
sound/hq/plats/hq1/train2.wav
sound/hq/plats/hq1/train_use1.wav
sound/hq/plats/hq1/ttrain1.wav
sound/hq/plats/hq1/ttrain2.wav
sound/hq/plats/hq1/ttrain3.wav
sound/hq/plats/hq1/ttrain4.wav
sound/hq/plats/hq1/ttrain5.wav
sound/hq/plats/hq1/ttrain6.wav
sound/hq/plats/hq1/ttrain7.wav
sound/hq/plats/hq1/ttrain_brake1.wav
sound/hq/plats/hq1/ttrain_start1.wav
sound/hq/player/hq1/breathe1.wav
sound/hq/player/hq1/breathe2.wav
sound/hq/player/hq1/geiger1.wav
sound/hq/player/hq1/geiger2.wav
sound/hq/player/hq1/geiger3.wav
sound/hq/player/hq1/geiger4.wav
sound/hq/player/hq1/heartbeat1.wav
sound/hq/player/hq1/pl_dirt1.wav
sound/hq/player/hq1/pl_dirt2.wav
sound/hq/player/hq1/pl_dirt3.wav
sound/hq/player/hq1/pl_dirt4.wav
sound/hq/player/hq1/pl_duct1.wav
sound/hq/player/hq1/pl_duct2.wav
sound/hq/player/hq1/pl_duct3.wav
sound/hq/player/hq1/pl_duct4.wav
sound/hq/player/hq1/pl_fallpain1.wav
sound/hq/player/hq1/pl_fallpain2.wav
sound/hq/player/hq1/pl_fallpain3.wav
sound/hq/player/hq1/pl_grate1.wav
sound/hq/player/hq1/pl_grate2.wav
sound/hq/player/hq1/pl_grate3.wav
sound/hq/player/hq1/pl_grate4.wav
sound/hq/player/hq1/pl_jump1.wav
sound/hq/player/hq1/pl_jump2.wav
sound/hq/player/hq1/pl_jumpland2.wav
sound/hq/player/hq1/pl_ladder1.wav
sound/hq/player/hq1/pl_ladder2.wav
sound/hq/player/hq1/pl_ladder3.wav
sound/hq/player/hq1/pl_ladder4.wav
sound/hq/player/hq1/pl_metal1.wav
sound/hq/player/hq1/pl_metal2.wav
sound/hq/player/hq1/pl_metal3.wav
sound/hq/player/hq1/pl_metal4.wav
sound/hq/player/hq1/pl_pain2.wav
sound/hq/player/hq1/pl_pain4.wav
sound/hq/player/hq1/pl_pain5.wav
sound/hq/player/hq1/pl_pain6.wav
sound/hq/player/hq1/pl_pain7.wav
sound/hq/player/hq1/pl_shell1.wav
sound/hq/player/hq1/pl_shell2.wav
sound/hq/player/hq1/pl_shell3.wav
sound/hq/player/hq1/pl_slosh1.wav
sound/hq/player/hq1/pl_slosh2.wav
sound/hq/player/hq1/pl_slosh3.wav
sound/hq/player/hq1/pl_slosh4.wav
sound/hq/player/hq1/pl_step1.wav
sound/hq/player/hq1/pl_step2.wav
sound/hq/player/hq1/pl_step3.wav
sound/hq/player/hq1/pl_step4.wav
sound/hq/player/hq1/pl_swim1.wav
sound/hq/player/hq1/pl_swim2.wav
sound/hq/player/hq1/pl_swim3.wav
sound/hq/player/hq1/pl_swim4.wav
sound/hq/player/hq1/pl_tile1.wav
sound/hq/player/hq1/pl_tile2.wav
sound/hq/player/hq1/pl_tile3.wav
sound/hq/player/hq1/pl_tile4.wav
sound/hq/player/hq1/pl_tile5.wav
sound/hq/player/hq1/pl_wade1.wav
sound/hq/player/hq1/pl_wade2.wav
sound/hq/player/hq1/pl_wade3.wav
sound/hq/player/hq1/pl_wade4.wav
sound/hq/player/hq1/sprayer.wav
sound/hq/sapience/changewach1.wav
sound/hq/sapience/changewach2.wav
sound/hq/sapience/paint1.wav
sound/hq/sapience/paint2.wav
sound/hq/sapience/paint3.wav
sound/hq/sapience/sissi1.wav
sound/hq/sapience/sissi1b.wav
sound/hq/sapience/truhnmensch1.wav
sound/hq/sapience/truhnmensch2.wav
sound/hq/sapience/wache1.wav
sound/hq/sapience/wache1b.wav
sound/hq/sapience/wache1c.wav
sound/hq/sapience/white1.wav
sound/hq/sapience/white2.wav
sound/hq/sapience/white3.wav
sound/hq/sapience/xmasdude.wav
sound/hq/sapience/xmasdude2.wav
sound/hq/weapons/hq1/357_cock1.wav
sound/hq/weapons/hq1/357_reload1.wav
sound/hq/weapons/hq1/357_shot1.wav
sound/hq/weapons/hq1/357_shot2.wav
sound/hq/weapons/hq1/bullet_hit1.wav
sound/hq/weapons/hq1/bullet_hit2.wav
sound/hq/weapons/hq1/cbar_hit1.wav
sound/hq/weapons/hq1/cbar_hit2.wav
sound/hq/weapons/hq1/cbar_hitbod1.wav
sound/hq/weapons/hq1/cbar_hitbod2.wav
sound/hq/weapons/hq1/cbar_hitbod3.wav
sound/hq/weapons/hq1/cbar_miss1.wav
sound/hq/weapons/hq1/dbarrel1.wav
sound/hq/weapons/hq1/debris1.wav
sound/hq/weapons/hq1/debris2.wav
sound/hq/weapons/hq1/debris3.wav
sound/hq/weapons/hq1/dryfire1.wav
sound/hq/weapons/hq1/egon_off1.wav
sound/hq/weapons/hq1/egon_run3.wav
sound/hq/weapons/hq1/egon_windup2.wav
sound/hq/weapons/hq1/electro4.wav
sound/hq/weapons/hq1/electro5.wav
sound/hq/weapons/hq1/electro6.wav
sound/hq/weapons/hq1/explode3.wav
sound/hq/weapons/hq1/explode4.wav
sound/hq/weapons/hq1/explode5.wav
sound/hq/weapons/hq1/g_bounce1.wav
sound/hq/weapons/hq1/g_bounce2.wav
sound/hq/weapons/hq1/g_bounce3.wav
sound/hq/weapons/hq1/g_bounce4.wav
sound/hq/weapons/hq1/g_bounce5.wav
sound/hq/weapons/hq1/gauss2.wav
sound/hq/weapons/hq1/glauncher.wav
sound/hq/weapons/hq1/glauncher2.wav
sound/hq/weapons/hq1/gren_cock1.wav
sound/hq/weapons/hq1/grenade_hit1.wav
sound/hq/weapons/hq1/grenade_hit2.wav
sound/hq/weapons/hq1/grenade_hit3.wav
sound/hq/weapons/hq1/hks1.wav
sound/hq/weapons/hq1/hks2.wav
sound/hq/weapons/hq1/hks3.wav
sound/hq/weapons/hq1/mine_activate.wav
sound/hq/weapons/hq1/mine_charge.wav
sound/hq/weapons/hq1/mine_deploy.wav
sound/hq/weapons/hq1/mortar.wav
sound/hq/weapons/hq1/mortarhit.wav
sound/hq/weapons/hq1/pl_gun1.wav
sound/hq/weapons/hq1/pl_gun2.wav
sound/hq/weapons/hq1/pl_gun3.wav
sound/hq/weapons/hq1/reload1.wav
sound/hq/weapons/hq1/reload2.wav
sound/hq/weapons/hq1/reload3.wav
sound/hq/weapons/hq1/ric1.wav
sound/hq/weapons/hq1/ric2.wav
sound/hq/weapons/hq1/ric3.wav
sound/hq/weapons/hq1/ric4.wav
sound/hq/weapons/hq1/ric5.wav
sound/hq/weapons/hq1/rocket1.wav
sound/hq/weapons/hq1/rocketfire1.wav
sound/hq/weapons/hq1/sbarrel1.wav
sound/hq/weapons/hq1/scock1.wav
sound/hq/weapons/hq1/sshell1.wav
sound/hq/weapons/hq1/sshell2.wav
sound/hq/weapons/hq1/sshell3.wav
sound/hq/weapons/hq1/xbow_fire1.wav
sound/hq/weapons/hq1/xbow_fly1.wav
sound/hq/weapons/hq1/xbow_hit1.wav
sound/hq/weapons/hq1/xbow_hit2.wav
sound/hq/weapons/hq1/xbow_hitbod1.wav
sound/hq/weapons/hq1/xbow_hitbod2.wav
sprites/hq/blacksmoke.spr
sprites/hq/die1.spr
sprites/hq/die2.spr
sprites/hq/die3.spr
sprites/hq/die4.spr
sprites/hq/die5.spr
sprites/hq/die6.spr
sprites/hq/rain.spr
sprites/hq/smoke.spr
sprites/hq/xfireball3.spr
sprites/hq1/aexplo.spr
sprites/hq1/bexplo.spr
sprites/hq1/cexplo.spr
sprites/hq1/dexplo.spr
sprites/hq1/eexplo.spr
sprites/hq1/explode1.spr
sprites/hq1/explode2.spr
sprites/hq1/fexplo.spr
sprites/hq1/fexplo1.spr
sprites/hq1/gexplo.spr
sprites/hq1/hexplo.spr
sprites/hq1/wxplo1.spr
sprites/hq1/zerogxplode.spr
s/a/d/i/s/m/walkthrough_hqa.txt
s/a/d/i/s/m/walkthrough_hqs.txt
s/a/d/i/s/m/walkthrough_hq.txt
s/a/d/i/s/m/l33t.txt
s/a/d/i/s/m/1255566.txt
s/a/d/i/s/m/125565.txt
s/a/d/i/s/m/38317.txt
s/a/d/i/s/m/13545.txt
s/a/d/i/s/m/12559.txt
s/a/d/i/s/m/12558.txt
s/a/d/i/s/m/12556.txt
s/a/d/i/s/m/12555.txt
s/a/d/i/s/m/666.txt
