// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

gfx/env/hqabk.tga
gfx/env/hqadn.tga
gfx/env/hqaft.tga
gfx/env/hqalf.tga
gfx/env/hqart.tga
gfx/env/hqaup.tga
gfx/env/hqnight2bk.tga
gfx/env/hqnight2dn.tga
gfx/env/hqnight2ft.tga
gfx/env/hqnight2lf.tga
gfx/env/hqnight2rt.tga
gfx/env/hqnight2up.tga
gfx/env/hqnightbk.tga
gfx/env/hqnightdn.tga
gfx/env/hqnightft.tga
gfx/env/hqnightlf.tga
gfx/env/hqnightrt.tga
gfx/env/hqnightup.tga
hoe.wad
hq2.wad
hq3.wad
maps/hq2_1.bsp
maps/hq2_10.bsp
maps/hq2_11.bsp
maps/hq2_12.bsp
maps/hq2_13.bsp
maps/hq2_14.bsp
maps/hq2_15.bsp
maps/hq2_16.bsp
maps/hq2_17.bsp
maps/hq2_2.bsp
maps/hq2_22.bsp
maps/hq2_23.bsp
maps/hq2_24.bsp
maps/hq2_25.bsp
maps/hq2_26.bsp
maps/hq2_27.bsp
maps/hq2_28.bsp
maps/hq2_29.bsp
maps/hq2_30.bsp
maps/hq2_4.bsp
maps/hq2_5.bsp
maps/hq2_7.bsp
maps/hq2_8.bsp
maps/hq2_9.bsp
maps/hq2_fox.bsp
maps/hq2_trilogy.bsp
models/hq/barney.mdl
models/hq/crossbow_bolt.mdl
models/hq/dragon.mdl
models/hq/greyslave.mdl
models/hq/hgrunt.mdl
models/hq/miniturret.mdl
models/hq/p_crossbow.mdl
models/hq/p_swordofsadism.mdl
models/hq/scientist.mdl
models/hq/turret.mdl
models/hq/v_357.mdl
models/hq/v_9mmarhqa.mdl
models/hq/v_9mmhandgun.mdl
models/hq/v_crossbow.mdl
models/hq/v_egon.mdl
models/hq/v_gauss.mdl
models/hq/v_rpg.mdl
models/hq/v_satchel.mdl
models/hq/v_satchel_radio.mdl
models/hq/v_shotgun.mdl
models/hq/v_swordofsadism.mdl
models/hq/v_tripmine.mdl
models/hq/w_9mmarclip.mdl
models/hq/w_battery.mdl
models/hq/w_crossbow_clip.mdl
models/hq/w_medkit.mdl
models/hq/w_suit.mdl
models/hq/w_swordofsadism.mdl
models/player/robo_hqa/robo_hqa.bmp
models/player/robo_hqa/robo_hqa.mdl
sound/hq/ambience/bj_01.wav
sound/hq/ambience/door_move1.wav
sound/hq/ambience/exist1.wav
sound/hq/ambience/exist2.wav
sound/hq/ambience/exist3.wav
sound/hq/ambience/exist4.wav
sound/hq/ambience/fan1.wav
sound/hq/ambience/glass_sound.wav
sound/hq/ambience/intro2.wav
sound/hq/ambience/jm_01.wav
sound/hq/ambience/ms_01.wav
sound/hq/ambience/ms_intro.wav
sound/hq/ambience/sil1.wav
sound/hq/ambience/sil2.wav
sound/hq/ambience/sil3.wav
sound/hq/ambience/sil_base.wav
sound/hq/ambience/sil_break2.wav
sound/hq/ambience/sil_drums.wav
sound/hq/ambience/sil_guitar.wav
sound/hq/ambience/sil_piano.wav
sound/hq/ambience/sil_piano2.wav
sound/hq/ambience/sil_string.wav
sound/hq/buttons/hq1/button1.wav
sound/hq/buttons/hq1/button11.wav
sound/hq/buttons/hq1/lightswitch2.wav
sound/hq/buttons/hq2/bell1.wav
sound/hq/buttons/hq2/blip1.wav
sound/hq/buttons/hq2/blip2.wav
sound/hq/buttons/hq2/button1.wav
sound/hq/buttons/hq2/button10.wav
sound/hq/buttons/hq2/button11.wav
sound/hq/buttons/hq2/button2.wav
sound/hq/buttons/hq2/button3.wav
sound/hq/buttons/hq2/button4.wav
sound/hq/buttons/hq2/button5.wav
sound/hq/buttons/hq2/button6.wav
sound/hq/buttons/hq2/button7.wav
sound/hq/buttons/hq2/button8.wav
sound/hq/buttons/hq2/button9.wav
sound/hq/buttons/hq2/latchlocked1.wav
sound/hq/buttons/hq2/latchlocked2.wav
sound/hq/buttons/hq2/latchunlocked1.wav
sound/hq/buttons/hq2/latchunlocked2.wav
sound/hq/buttons/hq2/lever1.wav
sound/hq/buttons/hq2/lever2.wav
sound/hq/buttons/hq2/lever3.wav
sound/hq/buttons/hq2/lever4.wav
sound/hq/buttons/hq2/lever5.wav
sound/hq/buttons/hq2/lightswitch2.wav
sound/hq/buttons/hq2/spark1.wav
sound/hq/buttons/hq2/spark2.wav
sound/hq/buttons/hq2/spark3.wav
sound/hq/buttons/hq2/spark4.wav
sound/hq/buttons/hq2/spark5.wav
sound/hq/buttons/hq2/spark6.wav
sound/hq/common/bodysplat.wav
sound/hq/common/hq2/bodydrop1.wav
sound/hq/common/hq2/bodydrop2.wav
sound/hq/common/hq2/bodydrop3.wav
sound/hq/common/hq2/bodydrop4.wav
sound/hq/common/hq2/bodysplat.wav
sound/hq/common/hq2/npc_step1.wav
sound/hq/common/hq2/npc_step2.wav
sound/hq/common/hq2/npc_step3.wav
sound/hq/common/hq2/npc_step4.wav
sound/hq/common/hq2/wpn_denyselect.wav
sound/hq/common/hq2/wpn_hudoff.wav
sound/hq/common/hq2/wpn_hudon.wav
sound/hq/common/hq2/wpn_moveselect.wav
sound/hq/common/hq2/wpn_select.wav
sound/hq/debris/hq2/beamstart1.wav
sound/hq/debris/hq2/beamstart10.wav
sound/hq/debris/hq2/beamstart11.wav
sound/hq/debris/hq2/beamstart14.wav
sound/hq/debris/hq2/beamstart15.wav
sound/hq/debris/hq2/beamstart2.wav
sound/hq/debris/hq2/beamstart3.wav
sound/hq/debris/hq2/beamstart4.wav
sound/hq/debris/hq2/beamstart5.wav
sound/hq/debris/hq2/beamstart6.wav
sound/hq/debris/hq2/beamstart7.wav
sound/hq/debris/hq2/beamstart8.wav
sound/hq/debris/hq2/beamstart9.wav
sound/hq/debris/hq2/bustceiling.wav
sound/hq/debris/hq2/bustconcrete1.wav
sound/hq/debris/hq2/bustconcrete2.wav
sound/hq/debris/hq2/bustcrate1.wav
sound/hq/debris/hq2/bustcrate2.wav
sound/hq/debris/hq2/bustcrate3.wav
sound/hq/debris/hq2/bustflesh1.wav
sound/hq/debris/hq2/bustflesh2.wav
sound/hq/debris/hq2/bustglass1.wav
sound/hq/debris/hq2/bustglass2.wav
sound/hq/debris/hq2/bustglass3.wav
sound/hq/debris/hq2/bustmetal1.wav
sound/hq/debris/hq2/bustmetal2.wav
sound/hq/debris/hq2/concrete1.wav
sound/hq/debris/hq2/concrete2.wav
sound/hq/debris/hq2/concrete3.wav
sound/hq/debris/hq2/flesh1.wav
sound/hq/debris/hq2/flesh2.wav
sound/hq/debris/hq2/flesh3.wav
sound/hq/debris/hq2/flesh5.wav
sound/hq/debris/hq2/flesh6.wav
sound/hq/debris/hq2/flesh7.wav
sound/hq/debris/hq2/glass1.wav
sound/hq/debris/hq2/glass2.wav
sound/hq/debris/hq2/glass3.wav
sound/hq/debris/hq2/glass4.wav
sound/hq/debris/hq2/metal1.wav
sound/hq/debris/hq2/metal2.wav
sound/hq/debris/hq2/metal3.wav
sound/hq/debris/hq2/metal4.wav
sound/hq/debris/hq2/metal5.wav
sound/hq/debris/hq2/metal6.wav
sound/hq/debris/hq2/pushbox1.wav
sound/hq/debris/hq2/pushbox2.wav
sound/hq/debris/hq2/pushbox3.wav
sound/hq/debris/hq2/wood1.wav
sound/hq/debris/hq2/wood2.wav
sound/hq/debris/hq2/wood3.wav
sound/hq/debris/hq2/wood4.wav
sound/hq/debris/hq2/zap1.wav
sound/hq/debris/hq2/zap2.wav
sound/hq/debris/hq2/zap3.wav
sound/hq/debris/hq2/zap4.wav
sound/hq/debris/hq2/zap5.wav
sound/hq/debris/hq2/zap6.wav
sound/hq/debris/hq2/zap7.wav
sound/hq/debris/hq2/zap8.wav
sound/hq/doors/hq1/doormove4.wav
sound/hq/doors/hq1/doormove9.wav
sound/hq/doors/hq2/aliendoor1.wav
sound/hq/doors/hq2/aliendoor2.wav
sound/hq/doors/hq2/aliendoor3.wav
sound/hq/doors/hq2/aliendoor4.wav
sound/hq/doors/hq2/aliendoor5.wav
sound/hq/doors/hq2/doormove1.wav
sound/hq/doors/hq2/doormove10.wav
sound/hq/doors/hq2/doormove2.wav
sound/hq/doors/hq2/doormove3.wav
sound/hq/doors/hq2/doormove4.wav
sound/hq/doors/hq2/doormove5.wav
sound/hq/doors/hq2/doormove6.wav
sound/hq/doors/hq2/doormove7.wav
sound/hq/doors/hq2/doormove8.wav
sound/hq/doors/hq2/doormove9.wav
sound/hq/doors/hq2/doorstop1.wav
sound/hq/doors/hq2/doorstop2.wav
sound/hq/doors/hq2/doorstop3.wav
sound/hq/doors/hq2/doorstop4.wav
sound/hq/doors/hq2/doorstop5.wav
sound/hq/doors/hq2/doorstop6.wav
sound/hq/doors/hq2/doorstop7.wav
sound/hq/doors/hq2/doorstop8.wav
sound/hq/doors/hq3/doormove3.wav
sound/hq/doors/hq3/doorstop3.wav
sound/hq/dragon/hc_alert1.wav
sound/hq/dragon/hc_attack1.wav
sound/hq/dragon/hc_attack2.wav
sound/hq/dragon/hc_attack3.wav
sound/hq/dragon/hc_die1.wav
sound/hq/dragon/hc_die2.wav
sound/hq/dragon/hc_headbite.wav
sound/hq/dragon/hc_idle1.wav
sound/hq/dragon/hc_idle2.wav
sound/hq/dragon/hc_idle3.wav
sound/hq/dragon/hc_idle4.wav
sound/hq/dragon/hc_idle5.wav
sound/hq/dragon/hc_pain1.wav
sound/hq/dragon/hc_pain2.wav
sound/hq/dragon/hc_pain3.wav
sound/hq/end/cred_move.wav
sound/hq/end/cred_stop.wav
sound/hq/end/end_dial1.wav
sound/hq/end/end_dial2.wav
sound/hq/end/end_dial3.wav
sound/hq/end/end_dial4.wav
sound/hq/end/end_dial5.wav
sound/hq/end/end_dial6.wav
sound/hq/end/insider.wav
sound/hq/end/mikrowelle.wav
sound/hq/end/tensecs.wav
sound/hq/fans/hq2/fan1.wav
sound/hq/fans/hq2/fan2.wav
sound/hq/fans/hq2/fan3.wav
sound/hq/fans/hq2/fan4.wav
sound/hq/fans/hq2/fan5.wav
sound/hq/grayslave/slv_alert1.wav
sound/hq/grayslave/slv_alert3.wav
sound/hq/grayslave/slv_alert4.wav
sound/hq/grayslave/slv_die1.wav
sound/hq/grayslave/slv_die2.wav
sound/hq/grayslave/slv_pain1.wav
sound/hq/grayslave/slv_pain2.wav
sound/hq/grayslave/slv_word1.wav
sound/hq/grayslave/slv_word2.wav
sound/hq/grayslave/slv_word3.wav
sound/hq/grayslave/slv_word4.wav
sound/hq/grayslave/slv_word5.wav
sound/hq/grayslave/slv_word6.wav
sound/hq/grayslave/slv_word7.wav
sound/hq/grayslave/slv_word8.wav
sound/hq/hq/man_die_part4.wav
sound/hq/hq2/abs_ost.wav
sound/hq/hq2/abs_tenn.wav
sound/hq/hq2/amb_ms.wav
sound/hq/hq2/amb_ms2.wav
sound/hq/hq2/amb_ost.wav
sound/hq/hq2/amb_ost2.wav
sound/hq/hq2/aud_bg1.wav
sound/hq/hq2/aud_sk1.wav
sound/hq/hq2/aud_sk2.wav
sound/hq/hq2/bj_exec2.wav
sound/hq/hq2/bj_exec3.wav
sound/hq/hq2/bj_exec_start.wav
sound/hq/hq2/ess_1.wav
sound/hq/hq2/ess_2.wav
sound/hq/hq2/ess_4.wav
sound/hq/hq2/flush.wav
sound/hq/hq2/hammer.wav
sound/hq/hq2/hq2_fox_monol.wav
sound/hq/hq2/life.wav
sound/hq/hq2/life2.wav
sound/hq/hq2/ms_ess1.wav
sound/hq/hq2/ms_ess2.wav
sound/hq/hq2/ms_ess3.wav
sound/hq/hq2/off_1.wav
sound/hq/hq2/off_ost.wav
sound/hq/hq2/off_ostig.wav
sound/hq/hq2/off_snd.wav
sound/hq/hq2/off_snd2.wav
sound/hq/hq2/off_speech1.wav
sound/hq/hq2/off_speech2.wav
sound/hq/hq2/pest_1.wav
sound/hq/hq2/pest_5.wav
sound/hq/hq2/pest_6_test.wav
sound/hq/hq2/pest_ost1.wav
sound/hq/hq2/pest_ost10.wav
sound/hq/hq2/pest_ost11.wav
sound/hq/hq2/pest_ost12.wav
sound/hq/hq2/pest_ost13.wav
sound/hq/hq2/pest_ost14.wav
sound/hq/hq2/pest_ost15.wav
sound/hq/hq2/pest_ost16.wav
sound/hq/hq2/pest_ost2.wav
sound/hq/hq2/pest_ost3.wav
sound/hq/hq2/pest_ost4.wav
sound/hq/hq2/pest_ost5.wav
sound/hq/hq2/pest_ost6.wav
sound/hq/hq2/pest_ost7.wav
sound/hq/hq2/pest_ost8.wav
sound/hq/hq2/pest_ost9.wav
sound/hq/hq2/quiz_no.wav
sound/hq/hq2/quiz_no2.wav
sound/hq/hq2/quiz_yes.wav
sound/hq/hq2/quiz_yes2.wav
sound/hq/hq2/sap_pflanzi.wav
sound/hq/hq2/snip.wav
sound/hq/hq_complete_soundtrack/01_intro.mp3
sound/hq/hq_complete_soundtrack/02_triste.mp3
sound/hq/hq_complete_soundtrack/04_hammertime.mp3
sound/hq/hq_complete_soundtrack/05_scream.mp3
sound/hq/hq_complete_soundtrack/06_offence.mp3
sound/hq/hq_complete_soundtrack/07_absence.mp3
sound/hq/hq_complete_soundtrack/08_ambience.mp3
sound/hq/hq_complete_soundtrack/09_sapience.mp3
sound/hq/hq_complete_soundtrack/10_beautiful_gray_sea.mp3
sound/hq/hq_complete_soundtrack/11_leaving_hope_academy.mp3
sound/hq/hq_complete_soundtrack/12_3ky.mp3
sound/hq/hq_complete_soundtrack/15_halfquake.mp3
sound/hq/hq_complete_soundtrack/19_regretful_victim.mp3
sound/hq/hq_complete_soundtrack/hq2_somos1.mp3
sound/hq/hq_complete_soundtrack/hq2_somos2.mp3
sound/hq/intro/logo.wav
sound/hq/intro/wavebase1.wav
sound/hq/intro/wavebase10.wav
sound/hq/intro/wavebase11.wav
sound/hq/intro/wavebase12.wav
sound/hq/intro/wavebase13.wav
sound/hq/intro/wavebase14.wav
sound/hq/intro/wavebase15.wav
sound/hq/intro/wavebase16.wav
sound/hq/intro/wavebase17.wav
sound/hq/intro/wavebase18.wav
sound/hq/intro/wavebase19.wav
sound/hq/intro/wavebase2.wav
sound/hq/intro/wavebase20.wav
sound/hq/intro/wavebase3.wav
sound/hq/intro/wavebase4.wav
sound/hq/intro/wavebase5.wav
sound/hq/intro/wavebase6.wav
sound/hq/intro/wavebase7.wav
sound/hq/intro/wavebase8.wav
sound/hq/intro/wavebase9.wav
sound/hq/materials.txt
sound/hq/patience/auri1.wav
sound/hq/patience/auri2.wav
sound/hq/patience/auri3.wav
sound/hq/patience/auri4.wav
sound/hq/patience/bgsnd1.wav
sound/hq/patience/bgsnd2.wav
sound/hq/patience/comm_ms.wav
sound/hq/patience/end1.wav
sound/hq/patience/end2.wav
sound/hq/patience/end3.wav
sound/hq/patience/end_snd.wav
sound/hq/patience/end_term.wav
sound/hq/patience/quiz_bg.wav
sound/hq/patience/tel1.wav
sound/hq/patience/tel2.wav
sound/hq/patience/tel3.wav
sound/hq/patience/tel4.wav
sound/hq/patience/tel_snd.wav
sound/hq/pestilence/bg.wav
sound/hq/pestilence/bj.wav
sound/hq/plats/hq2/bigmove1.wav
sound/hq/plats/hq2/bigmove2.wav
sound/hq/plats/hq2/bigstop1.wav
sound/hq/plats/hq2/bigstop2.wav
sound/hq/plats/hq2/elevbell1.wav
sound/hq/plats/hq2/elevmove1.wav
sound/hq/plats/hq2/elevmove2.wav
sound/hq/plats/hq2/elevmove3.wav
sound/hq/plats/hq2/freightmove1.wav
sound/hq/plats/hq2/freightmove2.wav
sound/hq/plats/hq2/freightstop1.wav
sound/hq/plats/hq2/heavymove1.wav
sound/hq/plats/hq2/heavystop1.wav
sound/hq/plats/hq2/heavystop2.wav
sound/hq/plats/hq2/platmove1.wav
sound/hq/plats/hq2/platstop1.wav
sound/hq/plats/hq2/rackmove1.wav
sound/hq/plats/hq2/railmove1.wav
sound/hq/plats/hq2/railstop1.wav
sound/hq/plats/hq2/squeekmove1.wav
sound/hq/plats/hq2/squeekstop1.wav
sound/hq/plats/hq2/talkmove1.wav
sound/hq/plats/hq2/talkmove2.wav
sound/hq/plats/hq2/talkstop1.wav
sound/hq/plats/hq2/train1.wav
sound/hq/plats/hq2/train2.wav
sound/hq/plats/hq2/train_use1.wav
sound/hq/plats/hq2/ttrain1.wav
sound/hq/plats/hq2/ttrain2.wav
sound/hq/plats/hq2/ttrain3.wav
sound/hq/plats/hq2/ttrain4.wav
sound/hq/plats/hq2/ttrain5.wav
sound/hq/plats/hq2/ttrain6.wav
sound/hq/plats/hq2/ttrain7.wav
sound/hq/plats/hq2/ttrain_brake1.wav
sound/hq/plats/hq2/ttrain_start1.wav
sound/hq/player/geiger1.wav
sound/hq/player/geiger2.wav
sound/hq/player/geiger3.wav
sound/hq/player/geiger4.wav
sound/hq/player/geiger5.wav
sound/hq/player/geiger6.wav
sound/hq/player/hq2/breathe1.wav
sound/hq/player/hq2/breathe2.wav
sound/hq/player/hq2/geiger1.wav
sound/hq/player/hq2/geiger2.wav
sound/hq/player/hq2/geiger3.wav
sound/hq/player/hq2/geiger4.wav
sound/hq/player/hq2/heartbeat1.wav
sound/hq/player/hq2/pl_dirt1.wav
sound/hq/player/hq2/pl_dirt2.wav
sound/hq/player/hq2/pl_dirt3.wav
sound/hq/player/hq2/pl_dirt4.wav
sound/hq/player/hq2/pl_duct1.wav
sound/hq/player/hq2/pl_duct2.wav
sound/hq/player/hq2/pl_duct3.wav
sound/hq/player/hq2/pl_duct4.wav
sound/hq/player/hq2/pl_fallpain1.wav
sound/hq/player/hq2/pl_fallpain2.wav
sound/hq/player/hq2/pl_fallpain3.wav
sound/hq/player/hq2/pl_grate1.wav
sound/hq/player/hq2/pl_grate2.wav
sound/hq/player/hq2/pl_grate3.wav
sound/hq/player/hq2/pl_grate4.wav
sound/hq/player/hq2/pl_jump1.wav
sound/hq/player/hq2/pl_jump2.wav
sound/hq/player/hq2/pl_jumpland2.wav
sound/hq/player/hq2/pl_ladder1.wav
sound/hq/player/hq2/pl_ladder2.wav
sound/hq/player/hq2/pl_ladder3.wav
sound/hq/player/hq2/pl_ladder4.wav
sound/hq/player/hq2/pl_metal1.wav
sound/hq/player/hq2/pl_metal2.wav
sound/hq/player/hq2/pl_metal3.wav
sound/hq/player/hq2/pl_metal4.wav
sound/hq/player/hq2/pl_pain2.wav
sound/hq/player/hq2/pl_pain4.wav
sound/hq/player/hq2/pl_pain5.wav
sound/hq/player/hq2/pl_pain6.wav
sound/hq/player/hq2/pl_pain7.wav
sound/hq/player/hq2/pl_shell1.wav
sound/hq/player/hq2/pl_shell2.wav
sound/hq/player/hq2/pl_shell3.wav
sound/hq/player/hq2/pl_slosh1.wav
sound/hq/player/hq2/pl_slosh2.wav
sound/hq/player/hq2/pl_slosh3.wav
sound/hq/player/hq2/pl_slosh4.wav
sound/hq/player/hq2/pl_step1.wav
sound/hq/player/hq2/pl_step2.wav
sound/hq/player/hq2/pl_step3.wav
sound/hq/player/hq2/pl_step4.wav
sound/hq/player/hq2/pl_swim1.wav
sound/hq/player/hq2/pl_swim2.wav
sound/hq/player/hq2/pl_swim3.wav
sound/hq/player/hq2/pl_swim4.wav
sound/hq/player/hq2/pl_tile1.wav
sound/hq/player/hq2/pl_tile2.wav
sound/hq/player/hq2/pl_tile3.wav
sound/hq/player/hq2/pl_tile4.wav
sound/hq/player/hq2/pl_tile5.wav
sound/hq/player/hq2/pl_wade1.wav
sound/hq/player/hq2/pl_wade2.wav
sound/hq/player/hq2/pl_wade3.wav
sound/hq/player/hq2/pl_wade4.wav
sound/hq/player/hq2/sprayer.wav
sound/hq/sapience/changewach1.wav
sound/hq/sapience/changewach2.wav
sound/hq/sapience/diary.wav
sound/hq/sapience/enddialog.wav
sound/hq/sapience/evilgiggle.wav
sound/hq/sapience/paint1.wav
sound/hq/sapience/paint2.wav
sound/hq/sapience/paint3.wav
sound/hq/sapience/ring.wav
sound/hq/sapience/sissi1.wav
sound/hq/sapience/sissi1b.wav
sound/hq/sapience/sss.wav
sound/hq/sapience/truhnmensch1.wav
sound/hq/sapience/truhnmensch2.wav
sound/hq/sapience/wache1.wav
sound/hq/sapience/wache1b.wav
sound/hq/sapience/wache1c.wav
sound/hq/sapience/white1.wav
sound/hq/sapience/white2.wav
sound/hq/sapience/white3.wav
sound/hq/sapience/xmasanzug.wav
sound/hq/sapience/xmasdude.wav
sound/hq/sapience/xmasdude2.wav
sound/hq/sapience/xmastree.wav
sound/hq/sapience/xmastreefree.wav
sound/hq/sapience/xmastreehurt.wav
sound/hq/somos/en1.wav
sound/hq/somos/en10.wav
sound/hq/somos/en11.wav
sound/hq/somos/en12.wav
sound/hq/somos/en13.wav
sound/hq/somos/en14.wav
sound/hq/somos/en15.wav
sound/hq/somos/en16.wav
sound/hq/somos/en2.wav
sound/hq/somos/en3.wav
sound/hq/somos/en4.wav
sound/hq/somos/en5.wav
sound/hq/somos/en6.wav
sound/hq/somos/en7.wav
sound/hq/somos/en8.wav
sound/hq/somos/en9.wav
sound/hq/somos/end_speech.wav
sound/hq/somos/explode.wav
sound/hq/somos/reload.wav
sound/hq/somos/shield.wav
sound/hq/violence/between.wav
sound/hq/violence/disturb1.wav
sound/hq/violence/disturb2.wav
sound/hq/violence/disturb3.wav
sound/hq/violence/disturb4.wav
sound/hq/violence/disturb5.wav
sound/hq/violence/disturb6.wav
sound/hq/violence/room1.wav
sound/hq/violence/room2.wav
sound/hq/violence/room3.wav
sound/hq/violence/room4.wav
sound/hq/weapons/hq2/357_cock1.wav
sound/hq/weapons/hq2/357_reload1.wav
sound/hq/weapons/hq2/357_shot1.wav
sound/hq/weapons/hq2/357_shot2.wav
sound/hq/weapons/hq2/bullet_hit1.wav
sound/hq/weapons/hq2/bullet_hit2.wav
sound/hq/weapons/hq2/dbarrel1.wav
sound/hq/weapons/hq2/debris1.wav
sound/hq/weapons/hq2/debris2.wav
sound/hq/weapons/hq2/debris3.wav
sound/hq/weapons/hq2/dryfire1.wav
sound/hq/weapons/hq2/egon_off1.wav
sound/hq/weapons/hq2/egon_run3.wav
sound/hq/weapons/hq2/egon_windup2.wav
sound/hq/weapons/hq2/electro4.wav
sound/hq/weapons/hq2/electro5.wav
sound/hq/weapons/hq2/electro6.wav
sound/hq/weapons/hq2/explode3.wav
sound/hq/weapons/hq2/explode4.wav
sound/hq/weapons/hq2/explode5.wav
sound/hq/weapons/hq2/g_bounce1.wav
sound/hq/weapons/hq2/g_bounce2.wav
sound/hq/weapons/hq2/g_bounce3.wav
sound/hq/weapons/hq2/g_bounce4.wav
sound/hq/weapons/hq2/g_bounce5.wav
sound/hq/weapons/hq2/gauss2.wav
sound/hq/weapons/hq2/glauncher.wav
sound/hq/weapons/hq2/glauncher2.wav
sound/hq/weapons/hq2/gren_cock1.wav
sound/hq/weapons/hq2/grenade_hit1.wav
sound/hq/weapons/hq2/grenade_hit2.wav
sound/hq/weapons/hq2/grenade_hit3.wav
sound/hq/weapons/hq2/hks1.wav
sound/hq/weapons/hq2/hks2.wav
sound/hq/weapons/hq2/hks3.wav
sound/hq/weapons/hq2/mine_charge.wav
sound/hq/weapons/hq2/mine_deploy.wav
sound/hq/weapons/hq2/mortar.wav
sound/hq/weapons/hq2/mortarhit.wav
sound/hq/weapons/hq2/pl_gun1.wav
sound/hq/weapons/hq2/pl_gun2.wav
sound/hq/weapons/hq2/pl_gun3.wav
sound/hq/weapons/hq2/reload1.wav
sound/hq/weapons/hq2/reload2.wav
sound/hq/weapons/hq2/reload3.wav
sound/hq/weapons/hq2/ric1.wav
sound/hq/weapons/hq2/ric2.wav
sound/hq/weapons/hq2/ric3.wav
sound/hq/weapons/hq2/ric4.wav
sound/hq/weapons/hq2/ric5.wav
sound/hq/weapons/hq2/rocket1.wav
sound/hq/weapons/hq2/rocketfire1.wav
sound/hq/weapons/hq2/sbarrel1.wav
sound/hq/weapons/hq2/scock1.wav
sound/hq/weapons/hq2/sshell1.wav
sound/hq/weapons/hq2/sshell2.wav
sound/hq/weapons/hq2/sshell3.wav
sound/hq/weapons/hq2/xbow_fire1.wav
sound/hq/weapons/hq2/xbow_fly1.wav
sound/hq/weapons/hq2/xbow_hit1.wav
sound/hq/weapons/hq2/xbow_hit2.wav
sound/hq/weapons/hq2/xbow_hitbod1.wav
sound/hq/weapons/hq2/xbow_hitbod2.wav
sound/hq/weapons/swordofsadism_hit1.wav
sound/hq/weapons/swordofsadism_hit2.wav
sound/hq/weapons/swordofsadism_hit3.wav
sound/hq/weapons/swordofsadism_hitbod1.wav
sound/hq/weapons/swordofsadism_hitbod2.wav
sound/hq/weapons/swordofsadism_hitbod3.wav
sound/hq/weapons/swordofsadism_miss1.wav
sprites/hq/blacksmoke.spr
sprites/hq/die1.spr
sprites/hq/die2.spr
sprites/hq/die3.spr
sprites/hq/die4.spr
sprites/hq/die5.spr
sprites/hq/die6.spr
sprites/hq/rain.spr
sprites/hq/smoke.spr
sprites/hq/weapon_9mmARhqa.txt
sprites/hq/weapon_swordofsadism.txt
sprites/hq/xfireball3.spr
sprites/hq/zerogxplode_hqa.spr
sprites/hq2/aexplo.spr
sprites/hq2/bexplo.spr
sprites/hq2/cexplo.spr
sprites/hq2/dexplo.spr
sprites/hq2/eexplo.spr
sprites/hq2/explode1.spr
sprites/hq2/explode2.spr
sprites/hq2/fexplo.spr
sprites/hq2/fexplo1.spr
sprites/hq2/hexplo.spr
sprites/hq2/wxplo1.spr
s/a/d/i/s/m/walkthrough_hqa.txt
s/a/d/i/s/m/walkthrough_hqs.txt
s/a/d/i/s/m/walkthrough_hq.txt
s/a/d/i/s/m/l33t.txt
s/a/d/i/s/m/1255566.txt
s/a/d/i/s/m/125565.txt
s/a/d/i/s/m/38317.txt
s/a/d/i/s/m/13545.txt
s/a/d/i/s/m/12559.txt
s/a/d/i/s/m/12558.txt
s/a/d/i/s/m/12556.txt
s/a/d/i/s/m/12555.txt
s/a/d/i/s/m/666.txt
