sound/tur/trippy.wav
sound/tur/lsd.wav
sound/tur/twospaces.wav
sound/tur/wl.wav
sound/tur/jazzy.wav
sound/omg/picard.wav
sound/omg/nomble.wav
sound/omg/sky.wav
sound/vox/endgame.wav
sound/vox/lol.wav
sound/vox/rofl.wav
sound/tur/voices.wav
sound/tur/ffff.wav
sound/tur/ffff2.wav
sound/player/knifed.wav
maps/secretcity4beta.res
maps/secretcity4beta_motd.txt
maps/secretcity4beta.cfg