sound/shell/sledgehammer.wav
sound/shell/stopwhining.wav
sound/tur/turrican.wav
sound/tur/mutecity.wav
sound/tur/slidje.wav
sound/tur/x2.wav
sound/tur/sc3.txt
sound/tur/gonome.txt
sound/tur/intruder.txt
sound/tur/kirk.wav
sound/tur/ice.wav
sound/tur/cave.wav
sound/omg/picard.wav
sound/omg/nomble.wav
gfx/env/LMcity_1bk.tga
gfx/env/LMcity_1up.tga
gfx/env/LMcity_1ft.tga
gfx/env/LMcity_1lf.tga
gfx/env/LMcity_1rt.tga
gfx/env/LMcity_1dn.tga
models/turr/turstatue.mdl
models/turr/p_keyboard.mdl
models/turr/w_keyboard.mdl
models/turr/v_keyboard.mdl
models/turr/turr.mdl
maps/secretcity3.cfg
maps/secretcity3.res