//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/killbox.html
halflife.wad
liquids.wad
xeno.wad
maps/killbox.bsp
maps/killbox.txt
