maps/sandbowl_r2.txt
maps/sandbowl_r2.bsp
maps/sandbowl_r2.res
sound/ambience/beep_1.wav
sound/ambience/goal_1.wav
sound/ambience/pickup_1.wav
overviews/sandbowl_r2.bmp
overviews/sandbowl_r2.txt
models/epromod/red_pack01.mdl
models/epromod/blue_pack01.mdl