// thirstfire.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (21):
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
halflife.wad
sound/ambience/cricket.wav
sound/ambience/siren.wav
sound/ambience/waterrun.wav
sound/thirstfire/coffee.wav
sound/thirstfire/lv_neon.wav
sound/thirstfire/open.wav
sound/thirstfire/secret.wav
sound/thirstfire/secreta1.wav
sound/thirstfire/secreta2.wav
sound/thirstfire/secreta3.wav
sound/thirstfire/thirstsiren.wav
sound/thirstfire/wind.wav
sprites/steam1.spr
xeno.wad

models/player/civilian_tf2c/civilian_tf2c.mdl
models/player/mercenary/mercenary.mdl
models/player/TFcivilian/TFcivilian.mdl
models/player/TFdemo/TFdemo.mdl
models/player/TFdemo2/TFdemo2.mdl
models/player/TFengineer/TFengineer.mdl
models/player/TFengineer2/TFengineer2.mdl
models/player/TFhvyweapon/TFhvyweapon.mdl
models/player/TFhvyweapon2/TFhvyweapon2.mdl
models/player/TFmedic/TFmedic.mdl
models/player/TFMedic2/TFmedic2.mdl
models/player/TFpyro/TFpyro.mdl
models/player/TFpyro2/TFpyro2.mdl
models/player/TFscout/TFscout.mdl
models/player/TFscout2/TFscout2.mdl
models/player/TFsniper/TFsniper.mdl
models/player/TFsniper2/TFsniper2.mdl
models/player/TFsoldier/TFsoldier.mdl
models/player/TFsoldier2/TFsoldier2.mdl
models/player/TFspy/TFspy.mdl
models/player/TFspy2/TFspy2.mdl
models/player/TFcivilian/TFcivilian.bmp
models/player/TFdemo/TFdemo.bmp
models/player/TFdemo2/TFdemo2.bmp
models/player/TFengineer/TFengineer.bmp
models/player/TFengineer2/TFengineer2.bmp
models/player/TFhvyweapon/TFhvyweapon.bmp
models/player/TFhvyweapon2/TFhvyweapon2.bmp
models/player/TFmedic/TFmedic.bmp
models/player/TFMedic2/TFmedic2.bmp
models/player/TFpyro/TFpyro.bmp
models/player/TFpyro2/TFpyro2.bmp
models/player/TFscout/TFscout.bmp
models/player/TFscout2/TFscout2.bmp
models/player/TFsniper/TFsniper.bmp
models/player/TFsniper2/TFsniper2.bmp
models/player/TFsoldier/TFsoldier.bmp
models/player/TFsoldier2/TFsoldier2.bmp
models/player/TFspy/TFspy.bmp
models/player/TFspy2/TFspy2.bmp
models/player/dm_colette/dm_colette.mdl
models/player/dm_colette/dm_colette.bmp
models/player/dm_gina/dm_gina.mdl
models/player/dm_gina/dm_gina.bmp
models/player/skeleton/skeleton.bmp
models/player/skeleton/skeleton.mdl
models/player/blue/blue.bmp
models/player/blue/blue.mdl
models/player/red/red.bmp
models/player/red/red.mdl
models/player/civilian_tf2c/civilian_tf2c.mdl
models/player/mercenary/mercenary.mdl
models/player/TFcivilian/TFcivilian.mdl
models/player/TFdemo/TFdemo.mdl
models/player/TFdemo2/TFdemo2.mdl
models/player/TFengineer/TFengineer.mdl
models/player/TFengineer2/TFengineer2.mdl
models/player/TFhvyweapon/TFhvyweapon.mdl
models/player/TFhvyweapon2/TFhvyweapon2.mdl
models/player/TFmedic/TFmedic.mdl
models/player/TFMedic2/TFmedic2.mdl
models/player/TFpyro/TFpyro.mdl
models/player/TFpyro2/TFpyro2.mdl
models/player/TFscout/TFscout.mdl
models/player/TFscout2/TFscout2.mdl
models/player/TFsniper/TFsniper.mdl
models/player/TFsniper2/TFsniper2.mdl
models/player/TFsoldier/TFsoldier.mdl
models/player/TFsoldier2/TFsoldier2.mdl
models/player/TFspy/TFspy.mdl
models/player/TFspy2/TFspy2.mdl
models/player/TFcivilian/TFcivilian.bmp
models/player/TFdemo/TFdemo.bmp
models/player/TFdemo2/TFdemo2.bmp
models/player/TFengineer/TFengineer.bmp
models/player/TFengineer2/TFengineer2.bmp
models/player/TFhvyweapon/TFhvyweapon.bmp
models/player/TFhvyweapon2/TFhvyweapon2.bmp
models/player/TFmedic/TFmedic.bmp
models/player/TFMedic2/TFmedic2.bmp
models/player/TFpyro/TFpyro.bmp
models/player/TFpyro2/TFpyro2.bmp
models/player/TFscout/TFscout.bmp
models/player/TFscout2/TFscout2.bmp
models/player/TFsniper/TFsniper.bmp
models/player/TFsniper2/TFsniper2.bmp
models/player/TFsoldier/TFsoldier.bmp
models/player/TFsoldier2/TFsoldier2.bmp
models/player/TFspy/TFspy.bmp
models/player/TFspy2/TFspy2.bmp
models/player/dm_colette/dm_colette.mdl
models/player/dm_colette/dm_colette.bmp
models/player/dm_gina/dm_gina.mdl
models/player/dm_gina/dm_gina.bmp
models/player/skeleton/skeleton.bmp
models/player/skeleton/skeleton.mdl
models/player/blue/blue.bmp
models/player/blue/blue.mdl
models/player/red/red.bmp
models/player/red/red.mdl
models/player/cannibal/Cannibal.bmp
models/player/cannibal/cannibal.mdl
models/player/ken/ken.bmp
models/player/ken/ken.mdl
models/player/botnes/botnes.mdl
models/player/botnes/botnes.bmp